# Generated by Django 3.2.7 on 2021-10-04 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_receita', models.DateField(auto_now=True)),
                ('descricao', models.CharField(max_length=50)),
                ('forma_receita', models.CharField(choices=[(1, 'salario'), (2, 'mesada'), (3, 'emprestimo')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recorrencia', models.BooleanField(default=False)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('data_emprestimo', models.DateField(auto_now=True)),
                ('data_pagamento', models.DateField()),
                ('descricao', models.CharField(max_length=50)),
                ('meio_pagametno', models.CharField(choices=[(1, 'boleto'), (2, 'dinheiro/debito'), (3, 'credito')], max_length=30)),
                ('valor_emprestimo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_apagar', models.DecimalField(decimal_places=2, max_digits=6)),
                ('parcelas', models.SmallIntegerField(default=1)),
                ('pago', models.BooleanField(default=False)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_despesa', models.DateField(auto_now=True)),
                ('descricao', models.CharField(max_length=50)),
                ('meio_pagametno', models.CharField(choices=[(1, 'boleto'), (2, 'dinheiro/debito'), (3, 'credito')], max_length=30)),
                ('tipo_despesa', models.CharField(choices=[(1, 'lanche'), (2, 'mercado'), (3, 'compras Online')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recorrencia', models.BooleanField(default=False)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
