# Generated by Django 3.2.7 on 2021-10-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='recorrencia',
        ),
        migrations.AddField(
            model_name='despesa',
            name='parcelas',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='meio_pagametno',
            field=models.CharField(choices=[('1', 'boleto'), ('2', 'dinheiro/debito'), ('3', 'credito')], max_length=30),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo_despesa',
            field=models.CharField(choices=[('1', 'lanche'), ('2', 'mercado'), ('3', 'compras Online')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='meio_pagametno',
            field=models.CharField(choices=[('1', 'boleto'), ('2', 'dinheiro/debito'), ('3', 'credito')], max_length=30),
        ),
        migrations.AlterField(
            model_name='receita',
            name='forma_receita',
            field=models.CharField(choices=[('1', 'salario'), ('2', 'mesada'), ('3', 'emprestimo')], max_length=30),
        ),
    ]
