# Generated by Django 3.2.7 on 2021-10-04 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0002_auto_20211004_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='id_user',
        ),
        migrations.AddField(
            model_name='despesa',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
