# Generated by Django 3.2.7 on 2021-10-08 18:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0008_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data_despesa',
            field=models.DateField(default=datetime.date(2021, 10, 8)),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=datetime.date(2021, 10, 8)),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_pagamento',
            field=models.DateField(default=datetime.date(2021, 10, 8)),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateField(default=datetime.date(2021, 10, 8)),
        ),
        migrations.AlterField(
            model_name='receita',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
