# Generated by Django 3.2.7 on 2021-10-08 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_auto_20211008_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data_despesa',
            field=models.DateField(blank=True, default=datetime.date(2021, 10, 8), null=True),
        ),
    ]
