# Generated by Django 3.2.7 on 2021-10-08 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_alter_despesa_data_despesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data_despesa',
            field=models.DateField(default=datetime.date(2021, 10, 8)),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
